### ISSUE TITLE
Crash on OSX + GTK3

### ISSUE THREAD

**Issue by wmvanvliet** [chimara/Chimara#49]
On OSX + GTK3, chimara crashes as soon as input is required.

**Comment by wmvanvliet** [comment]
could have to do something with threading. `gdk_theads_enter` is now deprecated, see #11

**Comment by ptomato** [comment]
I am pretty sure this is upstream bug https://bugzilla.gnome.org/show_bug.cgi?id=707699, which I've given up on. I think this is best solved by removing use of `gdk_threads_enter`, which I'll do as part of #11.

**Comment by ptomato** [comment]
Check the https://github.com/chimara/Chimara/tree/threading branch, this approach seems to work.

**Comment by wmvanvliet** [comment]
I'll test this once my mac gets back from the repair shop

**Comment by ptomato** [comment]
I tested this fairly thoroughly on my Mac as well at the time, but never got a chance to test it thoroughly on Linux. I did so now. I ran into one freeze, with the backtraces for the Glk thread and UI thread below. However, I don't think it's due to the `glk_threads_enter` refactor since it seems to be stopping while printing a GTK log message.

Anyway, if you agree, we can merge that branch and keep going.
---
**Glk thread**:
```
#0  0x00007f707dbe5bf9 in syscall ()
    at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f707e46095f in g_cond_wait () at /lib64/libglib-2.0.so.0
#2  0x00007f7080abb46f in get_appropriate_event (event=0x7f70649cb770)
    at /home/ptomato/workspace/Chimara/libchimara/event.c:68
#3  0x00007f7080abb699 in glk_select (event=0x7f70649cb770)
    at /home/ptomato/workspace/Chimara/libchimara/event.c:156
#4  0x00007f7065fa4218 in os_read_line (max=max@entry=120, buf=buf@entry=0x7f70649cb820, timeout=timeout@entry=0, width=width@entry=120, continued=<optimized out>) at /home/ptomato/workspace/Chimara/interpreters/frotz/glkmisc.c:432
#5  0x00007f7065f9fa3d in console_read_input (max=max@entry=120, buf=buf@entry=0x7f70649cb820, timeout=timeout@entry=0, continued=<optimized out>)
    at /home/ptomato/workspace/Chimara/interpreters/frotz/stream.c:26
#6  0x00007f7065fa00c8 in stream_read_input (max=max@entry=120, buf=buf@entry=0x7f70649cb820, timeout=<optimized out>, routine=<optimized out>, hot_keys=hot_keys@entry=0, no_scripting=0)
    at /home/ptomato/workspace/Chimara/interpreters/frotz/stream.c:421
#7  0x00007f7065f9c027 in z_read ()
    at /home/ptomato/workspace/Chimara/interpreters/frotz/input.c:217
#8  0x00007f7065f9d81e in interpret ()
    at /home/ptomato/workspace/Chimara/interpreters/frotz/process.c:301
#9  0x00007f7065f9c359 in glk_main ()
    at /home/ptomato/workspace/Chimara/interpreters/frotz/main.c:221
#10 0x00007f7080ab71b5 in glk_enter (startup=0x25f1060)
    at /home/ptomato/workspace/Chimara/libchimara/chimara-glk.c:1314
#11 0x00007f707e442b03 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#12 0x00007f707deb16ca in start_thread (arg=0x7f70649cc700)
    at pthread_create.c:333
#13 0x00007f707dbebf7f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```
**UI thread:**
```
#0  0x00007f707dbdbc4d in write () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f707db5ea57 in _IO_new_file_write (f=0x7f707dea5500 <_IO_2_1_stderr_>, data=0x7ffe414c9cf0, n=187) at fileops.c:1271
#2  0x00007f707db5f368 in new_do_write (to_do=<optimized out>, data=0x7ffe414c9cf0 "\n(chimara:12995): Gtk-\033[1;33mWARNING\033[0m **: Allocating size to GtkOverlay 0x2563580 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?\n", fp=0x7f707dea5500 <_IO_2_1_stderr_>)
    at fileops.c:526
#3  0x00007f707db5f368 in _IO_new_file_xsputn (f=0x7f707dea5500 <_IO_2_1_stderr_>, data=<optimized out>, n=187) at fileops.c:1350
#4  0x00007f707db34a45 in buffered_vfprintf (s=0x7f707dea5500 <_IO_2_1_stderr_>, format=<optimized out>, args=<optimized out>) at vfprintf.c:2346
#5  0x00007f707db31bf5 in _IO_vfprintf_internal (s=s@entry=0x7f707dea5500 <_IO_2_1_stderr_>, format=0x7f707e471a1f "%s\n", ap=ap@entry=0x7ffe414cc288)
    at vfprintf.c:1293
#6  0x00007f707dbfbbb9 in ___fprintf_chk (fp=0x7f707dea5500 <_IO_2_1_stderr_>, flag=1, format=<optimized out>) at fprintf_chk.c:35
#7  0x00007f707e422f8a in g_log_writer_standard_streams ()
    at /lib64/libglib-2.0.so.0
#8  0x00007f707e423077 in g_log_writer_default () at /lib64/libglib-2.0.so.0
#9  0x00007f707e4215bc in g_log_structured_array () at /lib64/libglib-2.0.so.0
#10 0x00007f707e4218b9 in g_log_structured () at /lib64/libglib-2.0.so.0
#11 0x00007f708051b0d9 in gtk_widget_size_allocate_with_baseline ()
    at /lib64/libgtk-3.so.0
#12 0x00007f7080ab6931 in allocate_recurse (win=0x269eb10, allocation=allocation@entry=0x7ffe414ccd90, spacing=spacing@entry=0)
    at /home/ptomato/workspace/Chimara/libchimara/chimara-glk.c:710
#13 0x00007f7080ab6aa4 in allocate_recurse (win=0x269ee30, allocation=allocation@entry=0x7ffe414cce20, spacing=0)
    at /home/ptomato/workspace/Chimara/libchimara/chimara-glk.c:597
#14 0x00007f7080ab7ef9 in chimara_glk_size_allocate (widget=0x2048500, allocation=0x7ffe414cceb0)
    at /home/ptomato/workspace/Chimara/libchimara/chimara-glk.c:733
#15 0x00007f708051af11 in gtk_widget_size_allocate_with_baseline ()
    at /lib64/libgtk-3.so.0
#16 0x00007f70802b26ac in gtk_box_size_allocate_no_center ()
    at /lib64/libgtk-3.so.0
#17 0x00007f70802b2a17 in gtk_box_allocate_contents () at /lib64/libgtk-3.so.0
#18 0x00007f70803087a8 in gtk_css_gadget_allocate () at /lib64/libgtk-3.so.0
#19 0x00007f70802b3e72 in gtk_box_size_allocate () at /lib64/libgtk-3.so.0
#20 0x00007f708051af11 in gtk_widget_size_allocate_with_baseline ()
    at /lib64/libgtk-3.so.0
#21 0x00007f708053163b in gtk_window_size_allocate () at /lib64/libgtk-3.so.0
#22 0x00007f707e6f33e5 in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#23 0x00007f707e704e04 in signal_emit_unlocked_R ()
    at /lib64/libgobject-2.0.so.0
#24 0x00007f707e70e05f in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#25 0x00007f707e70e43f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#26 0x00007f708051b107 in gtk_widget_size_allocate_with_baseline ()
    at /lib64/libgtk-3.so.0
#27 0x00007f708052ba2f in gtk_window_check_resize () at /lib64/libgtk-3.so.0
#28 0x00007f707e6f3614 in _g_closure_invoke_va () at /lib64/libgobject-2.0.so.0
#29 0x00007f707e70ddd9 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#30 0x00007f707e70e43f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#31 0x00007f70802fd698 in gtk_container_idle_sizer () at /lib64/libgtk-3.so.0
#32 0x00007f707e6f33e5 in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#33 0x00007f707e705432 in signal_emit_unlocked_R ()
    at /lib64/libgobject-2.0.so.0
#34 0x00007f707e70e05f in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#35 0x00007f707e70e43f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#36 0x00007f707fee3b93 in gdk_frame_clock_paint_idle () at /lib64/libgdk-3.so.0
#37 0x00007f707fecee78 in gdk_threads_dispatch () at /lib64/libgdk-3.so.0
#38 0x00007f707e41b88d in g_timeout_dispatch () at /lib64/libglib-2.0.so.0
#39 0x00007f707e41ae42 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#40 0x00007f707e41b1c0 in g_main_context_iterate.isra ()
    at /lib64/libglib-2.0.so.0
#41 0x00007f707e41b4e2 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#42 0x00007f70803c2815 in gtk_main () at /lib64/libgtk-3.so.0
#43 0x0000000000404034 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/ptomato/workspace/Chimara/player/main.c:244
```

**Comment by wmvanvliet** [comment]
The threading branch works great on my linux system. No issues during the build, no crashes yet. +1 for merging this.
